
INSERT INTO `settings` (
  `id`, `options`, `created_at`, `updated_at`
)
VALUES (
    1, '{\"seo\": {\"ogImage\": null, \"ogTitle\": null, \"metaTags\": null, \"metaTitle\": null, \"canonicalUrl\": null, \"ogDescription\": null, \"twitterHandle\": null, \"metaDescription\": null, \"twitterCardType\": null}, \"logo\": {\"id\": \"862\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/860/PickBazar.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/860/conversions/PickBazar-thumbnail.jpg\"}, \"useOtp\": false,\"useGoogleMap\": false, \"currency\": \"USD\", \"taxClass\": \"1\", \"siteTitle\": \"Pickbazar\", \"deliveryTime\": [{\"title\": \"Express Delivery\", \"description\": \"90 min express delivery\"}, {\"title\": \"Morning\", \"description\": \"8.00 AM - 11.00 AM\"}, {\"title\": \"Noon\", \"description\": \"11.00 AM - 2.00 PM\"}, {\"title\": \"Afternoon\", \"description\": \"2.00 PM - 5.00 PM\"}, {\"title\": \"Evening\", \"description\": \"5.00 PM - 8.00 PM\"}], \"signupPoints\": 100, \"siteSubtitle\": \"Your next ecommerce\", \"shippingClass\": \"1\", \"contactDetails\": {\"contact\": \"+129290122122\", \"emailAddress\": \"demo@demo.com\", \"socials\": [{\"url\": \"https://www.facebook.com/\", \"icon\": \"FacebookIcon\"}, {\"url\": \"https://twitter.com/home\", \"icon\": \"TwitterIcon\"}, {\"url\": \"https://www.instagram.com\", \"icon\": \"InstagramIcon\"}], \"website\": \"https://redq.io\", \"location\": {\"lat\": 42.9585979, \"lng\": -76.90872019999999, \"zip\": null, \"city\": null, \"state\": \"NY\", \"country\": \"United States\", \"formattedAddress\": \"NY State Thruway, New York, USA\"}}, \"minimumOrderAmount\": 0, \"currencyToWalletRatio\": 3, \"maximumQuestionLimit\": 5, "useCashOnDelivery": true,\"freeShipping\": false,\"freeShippingAmount\": 0, "paymentGateway": [{"name": "stripe", "title": "Stripe"}], "defaultPaymentGateway": "stripe", "isProductReview":false, \"useMustVerifyEmail\":false, "useEnableGateway":false,\"currencyOptions\": {\"formation\": \"en-US\", \"fractions\": 2},"\guestCheckout\": true,\"smsEvent\": {\"admin\":\{\"statusChangeOrder\":true,\"refundOrder\":true},\"vendor\":\{\"statusChangeOrder\":true,\"refundOrder\":true},\"customer\":\{\"statusChangeOrder\":true,\"refundOrder\":true}},\"emailEvent\":{\"admin\":{},\"vendor\":{},\"customer\":{}}, "useAi": false,"defaultAi": "openai","maxShopDistance": 1000}',
    '2021-03-24 15:30:18', '2022-01-15 19:02:50'
);

