INSERT INTO `shops` (
    `id`,
    `owner_id`,
    `name`,
    `slug`,
    `description`,
    `cover_image`,
    `logo`,
    `is_active`,
    `address`,
    `settings`,
    `notifications`,
    `created_at`,
    `updated_at`
  )
VALUES (
    1,
    1,
    'Furniture Shop',
    'furniture-shop',
    'The furniture shop is the best shop around the city. This is being run under the store owner and our aim is to provide quality product and hassle free customer service.',
    '{\"id\": \"885\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/883/Untitled-6.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/883/conversions/Untitled-6-thumbnail.jpg\"}',
    '{\"id\": \"884\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/882/Furniture.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/882/conversions/Furniture-thumbnail.jpg\"}',
    1,
    '{\"zip\": \"08753\", \"city\": \"East Dover\", \"state\": \"New Jersey\", \"country\": \"USA\", \"street_address\": \"588  Finwood Road\"}',
    '{\"contact\": \"21342121221\", \"socials\": [{\"url\": \"https://www.instagram.com/\", \"icon\": \"InstagramIcon\"}], \"website\": \"https://redq.io/\", \"location\": {\"lat\": 40.757272, \"lng\": -74.089508, \"city\": \"Kearny\", \"state\": \"NJ\", \"country\": \"United States\", \"formattedAddress\": \"New Jersey Turnpike, Kearny, NJ, USA\"}}',
    NULL,
    '2021-06-27 03:46:14',
    '2023-10-12 04:40:13'
  ),
  (
    2,
    1,
    'Clothing Shop',
    'clothing-shop',
    'The clothing shop is the best shop around the city. This is being run under the store owner and our aim is to provide quality product and hassle free customer service.',
    '{\"id\": \"886\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/884/Untitled-4.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/884/conversions/Untitled-4-thumbnail.jpg\"}',
    '{\"id\": \"896\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/894/fashion.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/894/conversions/fashion-thumbnail.jpg\"}',
    1,
    '{\"country\":\"USA\",\"city\":\"Lincoln\",\"state\":\"Illinois\",\"zip\":\"62656\",\"street_address\":\"4885  Spring Street\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"212901921221\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"https:\\/\\/www.facebook.com\\/\"}],\"location\":{\"lat\":40.1576691,\"lng\":-89.38529779999999,\"city\":\"Lincoln\",\"state\":\"IL\",\"country\":\"United States\",\"formattedAddress\":\"IL-121, Lincoln, IL, USA\"}}',
    NULL,
    '2021-06-27 03:47:10',
    '2023-10-19 06:51:41'
  ),
  (
    3,
    1,
    'Bags Shop',
    'bags-shop',
    'The Bag shop is the best shop around the city. This is being run under the store owner and our aim is to provide quality product and hassle free customer service.',
    '{\"id\": \"889\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/887/Untitled-1-%281%29.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/887/conversions/Untitled-1-%281%29-thumbnail.jpg\"}',
    '{\"id\": \"888\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/886/Backpack.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/886/conversions/Backpack-thumbnail.jpg\"}',
    1,
    '{\"country\":\"USA\",\"city\":\"Michigan\",\"state\":\"Alabama\",\"zip\":\"35203\",\"street_address\":\"1740  Bedford Street\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"212901921221\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"https:\\/\\/www.facebook.com\\/\"},{\"icon\":\"InstagramIcon\",\"url\":\"https:\\/\\/www.instagram.com\\/\"}],\"location\":{\"lat\":-37.1374024,\"lng\":174.9685924,\"zip\":\"2579\",\"city\":\"Ramarama\",\"state\":\"Auckland\",\"country\":\"New Zealand\",\"formattedAddress\":\"Waharau Lane, Ramarama 2579, New Zealand\"}}',
    NULL,
    '2021-06-27 03:47:23',
    '2023-10-19 06:52:14'
  ),
  (
    4,
    1,
    'Makeup Shop',
    'makeup-shop',
    'The makeup shop is the best shop around the city. This is being run under the store owner and our aim is to provide quality product and hassle free customer service.',
    '{\"id\": \"890\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/888/Untitled-3.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/888/conversions/Untitled-3-thumbnail.jpg\"}',
    '{\"id\": \"891\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/889/Makeup.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/889/conversions/Makeup-thumbnail.jpg\"}',
    1,
    '{\"country\":\"USA\",\"city\":\"Metairie\",\"state\":\"Louisiana\",\"zip\":\"70001\",\"street_address\":\"2960  Rose Avenue\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"7196321822\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"InstagramIcon\",\"url\":\"https:\\/\\/www.instagram.com\\/\"},{\"icon\":\"TwitterIcon\",\"url\":\"https:\\/\\/www.twitter.com\\/\"}],\"location\":{\"lat\":51.5176117,\"lng\":-0.210149,\"state\":\"England\",\"country\":\"United Kingdom\",\"formattedAddress\":\"Ladbroke Grove, London, UK\"}}',
    NULL,
    '2021-06-27 03:47:49',
    '2023-10-19 07:04:43'
  ),
  (
    5,
    1,
    'Bakery Shop',
    'bakery-shop',
    'The bakery shop is the best shop around the city. This is being run under the store owner and our aim is to provide fresh and quality product and hassle free customer service.',
    '{\"id\": \"895\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/893/Untitled-5.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/893/conversions/Untitled-5-thumbnail.jpg\"}',
    '{\"id\": \"892\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/890/bakery.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/890/conversions/bakery-thumbnail.jpg\"}',
    1,
    '{\"zip\": \"27801\", \"city\": \"Rocky Mount\", \"state\": \"Carolina\", \"country\": \"USA\", \"street_address\": \"4422  Fort Street\"}',
    '{\"contact\": \"12902232121\", \"socials\": [{\"url\": \"https://www.facebook.com/\", \"icon\": \"FacebookIcon\"}, {\"url\": \"https://www.instagram.com/\", \"icon\": \"InstagramIcon\"}], \"website\": \"https://redq.io/\", \"location\": {\"lat\": 40.7315115, \"lng\": -73.99582730000002, \"city\": \"New York\", \"state\": \"NY\", \"country\": \"United States\", \"formattedAddress\": \"Washington Mews, New York, NY, USA\"}}',
    NULL,
    '2021-06-27 03:48:11',
    '2023-10-12 04:44:06'
  ),
  (
    6,
    1,
    'Grocery Shop',
    'grocery-shop',
    'The grocery shop is the best shop around the city. This is being run under the store owner and our aim is to provide fresh and quality product and hassle free customer service.',
    '{\"id\": \"894\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/892/Untitled-2.jpg\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/892/conversions/Untitled-2-thumbnail.jpg\"}',
    '{\"id\": \"893\", \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/891/Group-36321.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/891/conversions/Group-36321-thumbnail.jpg\"}',
    1,
    '{\"country\":\"USA\",\"city\":\"Freeport\",\"state\":\"Illinois\",\"zip\":\"61032\",\"street_address\":\"1986  Spinnaker Lane\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"5619327220\",\"website\":\"https:\\/\\/redq.io\",\"socials\":[{\"icon\":\"FacebookIcon\",\"url\":\"https:\\/\\/www.facebook.com\\/\"},{\"icon\":\"InstagramIcon\",\"url\":\"https:\\/\\/www.instagram.com\\/\"},{\"icon\":\"TwitterIcon\",\"url\":\"https:\\/\\/www.twitter.com\\/\"}],\"location\":{\"lat\":38.9032325,\"lng\":-77.0211068,\"city\":\"Washington\",\"state\":\"DC\",\"country\":\"United States\",\"formattedAddress\":\"New York Ave NW, Washington, DC, USA\"}}',
    NULL,
    '2021-06-27 03:48:23',
    '2023-10-19 07:05:23'
  ),
  (
    7,
    1,
    'Books Shop',
    'books-shop',
    'This is the book shop. All the publications sells their book under this book shop',
    '{\"id\": 1374, \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1374/Cover.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1374/conversions/Cover-thumbnail.jpg\"}',
    '{\"id\": 1613, \"original\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1613/Publisher-logo.png\", \"thumbnail\": \"https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1613/conversions/Publisher-logo-thumbnail.jpg\"}',
    1,
    '{\"country\":\"Switzerland\",\"city\":\"zurich\",\"state\":\"California\",\"zip\":\"8021\",\"street_address\":\"44444\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"7033542601\",\"website\":\"demodemo.com\",\"location\":[],\"socials\":[]}',
    NULL,
    '2021-12-07 16:47:07',
    '2023-10-25 03:30:21'
  ),
  (
    9,
    1,
    'Gadget',
    'gadget',
    'The Gadget shop is the best shop in the city. This is being run under the store owner and our aim is to provide quality product and hassle-free customer service.',
    '{\"thumbnail\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1723\\/conversions\\/Gadget-banner-thumbnail.jpg\",\"original\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1723\\/Gadget-banner.png\",\"id\":1723,\"file_name\":\"Gadget-banner.png\"}',
    '{\"thumbnail\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1722\\/conversions\\/Gadget-thumbnail.jpg\",\"original\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1722\\/Gadget.jpg\",\"id\":1722,\"file_name\":\"Gadget.jpg\"}',
    1,
    '{\"country\":\"USA\",\"city\":\"Michigan\",\"state\":\"Alabama\",\"zip\":\"35203\",\"street_address\":\"1740  Bedford Street\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"7708140768\",\"website\":\"test-site.com\",\"location\":[],\"socials\":[]}',
    NULL,
    '2023-10-02 08:38:16',
    '2023-10-19 06:54:37'
  ),
  (
    11,
    1,
    'Medicine',
    'medicine',
    NULL,
    '{\"thumbnail\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1787\\/conversions\\/Medicine-banner-thumbnail.jpg\",\"original\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1787\\/Medicine-banner.png\",\"id\":1787,\"file_name\":\"Medicine-banner.png\"}',
    '{\"thumbnail\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1786\\/conversions\\/Medicine-thumbnail.jpg\",\"original\":\"https:\\/\\/pickbazarlaravel.s3.ap-southeast-1.amazonaws.com\\/1786\\/Medicine.jpg\",\"id\":1786,\"file_name\":\"Medicine.jpg\"}',
    1,
    '{\"country\":\"United States\",\"city\":\"Manhattan\",\"state\":\"New York\",\"zip\":\"12332\",\"street_address\":\"East Avenue 1743, West Tower\"}',
    '{\"notifications\":{\"email\":null},\"contact\":\"8139982265\",\"website\":\"test.com\",\"location\":[],\"socials\":[]}',
    NULL,
    '2023-10-02 17:42:55',
    '2023-10-19 07:02:38'
  );